[package]
name = "cosmic-player"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1"
paste = "1"
serde = { version = "1", features = ["serde_derive"] }
tokio = "1"
url = "2"
# ffmpeg
cpal = { version = "0.15", optional = true }
ffmpeg-next = { version = "7", optional = true }
# Internationalization
i18n-embed = { version = "0.13", features = ["fluent-system", "desktop-requester"] }
i18n-embed-fl = "0.6"
rust-embed = "6"
# Logging
env_logger = "0.10"
log = "0.4"
lexopt = "0.3"

[dependencies.iced_video_player]
git = "https://github.com/jackpot51/iced_video_player.git"
branch = "cosmic"
optional = true

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "winit"]

[dependencies.smol_str]
version = "0.2.1"
features = ["serde"]

[features]
default = ["gstreamer", "wgpu"]
ffmpeg = ["dep:cpal", "dep:ffmpeg-next"]
gstreamer = ["dep:iced_video_player", "wgpu"]
wgpu = ["libcosmic/wgpu"]

[profile.release-with-debug]
inherits = "release"
debug = true

# [patch.'https://github.com/jackpot51/iced_video_player']
# iced_video_player = { path = "../../iced_video_player" }

# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }

